services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - 5432:5432
    container_name: postgres_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    restart: unless-stopped
    container_name: nodejs-api
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "postgres:database"
    environment:
      - PGHOST=database
    env_file:
      - .env
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      postgres:
        condition: service_healthy
